set up hyprland on wayland

diff --git a/bin/brightctl b/bin/brightctl
--- a/bin/brightctl
+++ b/bin/brightctl
@@ -2,23 +2,33 @@
 # vim: syn=bash ft=bash
 
 if [[ ! $1 =~ ^[+-][1-9][0-9]?$ ]]; then
-    echo "Invalid argument. Use +N or -N where N is 1-99."
-    exit 1
+  echo "Invalid argument. Use +N or -N where N is 1-99."
+  exit 1
 fi
 
 sign=${1:0:1}
 value=${1:1}
 
 if [ "$sign" = "+" ]; then
-    light -A "$value"
+  light -A "$value"
 else
-    light -U "$value"
+  light -U "$value"
 fi
 
-brightness=$(light -G | cut -d'.' -f1)
-dunstify \
-    -a "brightctl" \
-    -u "low" \
-    -h "string:x-dunst-stack-tag:brightctl" \
-    -i "/run/current-system/sw/share/icons/WhiteSur-dark/status/symbolic/display-brightness-symbolic.svg" \
-    "brightness = $brightness%" ""
+brightness=$(printf "%.0f" "$(light -G)")
+((brightness > 100)) && brightness=100
+
+if [[ "$brightness" -ge 70 ]]; then
+  icon="󰃠"
+elif [[ "$brightness" -ge 40 ]]; then
+  icon="󰃟"
+else
+  icon="󰃞"
+fi
+
+notify-send \
+  -a "brightctl" \
+  -u "low" \
+  -h "string:x-dunst-stack-tag:brightctl" \
+  -h "int:value:${brightness}" \
+  "$icon  ${brightness}%"
