fix: modify script to use realpath

diff --git a/scripts/path-to-url b/scripts/path-to-url
--- a/scripts/path-to-url
+++ b/scripts/path-to-url
@@ -1,10 +1,10 @@
 #! /bin/bash
 
-file_path="$1"
+file_path=$(realpath "$1")
 
-if [ ! -f "$file_path" ]; then
-  echo "Error: File not found" >&2
-  return 1
+if [ ! -e "$file_path" ]; then
+  echo "Error: File or directory not found" >&2
+  exit 1
 fi
 
 absolute_path=$(realpath "$file_path")
